/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractPascalIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PascalIdeModule extends AbstractPascalIdeModule {
}
